### ISSUE TITLE
Unable to open application

### ISSUE THREAD

**Issue by Gasnik** [xf86cfg/AMIQueueMonitor#1]
When I'm trying to open this software, I am getting an error: "Couldn't load style settings"
Windows 10 Pro, tried on 2 machines

**Comment by Marcelas751** [comment]
121+122 строка Configuration.cs

**Comment by xkarloos** [comment]
same issue, any solution? how can I fix it?

**Comment by Marcelas751** [comment]
я думаю нужно переписывать код в Configuration.cs чтобы правильно парсить данные из конфига

**Comment by xf86cfg** [comment]
Привет,
А что с ним не так? Я давно не занимался этим проектом

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Marcelas751** [comment]
Щас скрин дам

**Comment by Marcelas751** [comment]
PointConverter похоже неправильно распарсил дефолтное значение из конфига для указателя FormOrigin типа System.Drawing.Point (но это только одна ошибка, там в следующих строках тоже криво распарсились значения).
![image](https://user-images.githubusercontent.com/40628504/143014482-dc6e4f22-1ef7-4c64-b21a-d498904c5605.png)

**Comment by xf86cfg** [comment]
Ясно.
Можешь создать пулл реквест с фиксом?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Marcelas751** [comment]
Могу присобачить костыль)

**Comment by Marcelas751** [comment]
Ладно, я подумаю что можно с этим с делать

**Comment by xf86cfg** [comment]
Давай :)
Только сделай пулл реквест плз.
Если нет, то я гляну, но не могу обещать когда, скорее всего не раньше следующей недели.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Marcelas751** [comment]
Пока вкратце
```
                string str = ConfigurationManager.AppSettings["FormOrigin"];
                string[] coords = str.Split(',');
                WindowTitle = ConfigurationManager.AppSettings["WindowTitle"];
                var fontConverter = new FontConverter();
                ConsoleFont = fontConverter.ConvertFromString(ConfigurationManager.AppSettings["ConsoleFont"]) as Font;
                TableHeadersFont = fontConverter.ConvertFromString(ConfigurationManager.AppSettings["TableHeadersFont"]) as Font;
                TableRowsFont = fontConverter.ConvertFromString(ConfigurationManager.AppSettings["TableRowsFont"]) as Font;
                StateIndicatorsFont = fontConverter.ConvertFromString(ConfigurationManager.AppSettings["StateIndicatorsFont"]) as Font;
                TableHeadersHeight = int.Parse(ConfigurationManager.AppSettings["TableHeadersHeight"]);
                FormOrigin = new Point(int.Parse(coords[0]), int.Parse(coords[1]));
```

**Comment by Marcelas751** [comment]
![image](https://user-images.githubusercontent.com/40628504/143197674-2389cec5-4e0b-4972-b284-a3d6273fe63e.png)
Я готов впринципе

**Comment by xf86cfg** [comment]
Отлично, создай Pull Request плз

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by xf86cfg** [comment]
Для создания PR:
1. Сделай fork репозитория (справа сверху кнопка fork)
2. После форка тебя перенаправит в форкнутый репозиторий в твоём аккаунте
3. Склонируй репозиторий локально на машину
4. Создай новую ветку к примеру git checkout -b config-fix
5. Внеси изменения в ветку и закомить
6. git push к себе в репозиторий
7. Дальше пулл реквест из твоего форкнутого репозитория в основной

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Marcelas751** [comment]
done

**Comment by xf86cfg** [comment]
Closed with https://github.com/xf86cfg/AMIQueueMonitor/pull/2
